language: go

before_install:
- go get code.google.com/p/go.tools/cmd/vet
- go get github.com/golang/lint/golint

script: 
- go test -v -race ./...
- go tool vet -all=true -v=true .
- golint ./...

# have travis use a docker container for this build
sudo: false