language: go

matrix:
  include:
    - go: "1.2"
      env: VET_PACKAGE=code.google.com/p/go.tools/cmd/vet
    - go: "1.3"
      env: VET_PACKAGE=code.google.com/p/go.tools/cmd/vet
    - go: "1.4"
      env: VET_PACKAGE=golang.org/x/tools/cmd/vet

before_script:
  - go get $VET_PACKAGE
  - go get golang.org/x/lint/golint

script: 
  - go test -v -race ./...
  - go tool vet -all=true -v=true .
  - golint ./...

# have travis use a docker container for this build
sudo: false